### PR TITLE
Add icepyx to GIS Remote Sensing Software section

### PR DESCRIPTION
**Pull request by weiji14**
`icepyx` is a Python package for obtaining and working with ICESat-2 laser altimetry data. Website is at https://github.com/icesat2py/icepyx and https://icepyx.readthedocs.io. Cc @JessicaS11

P.S. I'd recommend using ['Squash and merge'](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits) to merge in Pull Requests. This will help keep the git history tidy :grin: Oh, and thanks @jlandmann for starting this great initiative on Cryolist!

### CODE REVIEW

**Comment by jlandmann** [comment]
Hi Wei Ji! 
Thanks a lot for contribution! Go spread the word so that we can collect more awesome tools :-)

**Comment by weiji14** [comment]
Oh I'm sure there will be a lot coming soon :wink: Let me know if the tide gets too much, I'm happy to help out with maintaining this repo too.

**Comment by jlandmann** [comment]
Cool, thanks a lot! I can add you to the organization as well!

**Comment by weiji14** [comment]
Sure, feel free to add me in :grin:

**Pull request merged**
